title: Wallpaper Reactor
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
color_scheme: dark

url: https://likeich.github.io/

# aux_links:
#   Releases: /releases/

ga_tracking: "G-YYB483JREW"
